### ISSUE TITLE
phone automatically locks when making a call

### ISSUE THREAD

**Issue by Blatteman** [xen0n/android_device_meizu_arale#7] opened 2015-10-12 10:03 UTC
When making a call, the phone locks automatically and it is impossible to hang up, the only way is to turn off the phone.

**Comment by xen0n** [comment] 2015-10-13 08:19
Hi, this is known and is caused by incorrect initialization of proximity sensor. Actual fix is pretty hard and I'm working on this right now, but don't expect anything soon; the fix _will_ be done as it's extremely annoying for me too. BTW you can enable the setting "hang up by power button" in the meanwhile, although you still cannot access the dialpad while making a call this way.

**Comment by Blatteman** [comment] 2015-10-13 13:48
Thanks for the hint ! 

Le 13 octobre 2015 10:19:04 GMT+02:00, Wang Xuerui notifications@github.com a écrit :

> Hi, this is known and is caused by incorrect initialization of
> proximity sensor. Actual fix is pretty hard and I'm working on this
> right now, but don't expect anything soon; the fix _will_ be done as
> it's extremely annoying for me too. BTW you can enable the setting
> "hang up by power button" in the meanwhile, although you still cannot
> access the dialpad while making a call this way.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/xen0n/android_device_meizu_arale/issues/7#issuecomment-147642989

## 

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by xen0n** [comment] 2015-10-13 16:34
Fsck yeah, I echoed the incorrect (drifted by ~150, which really should be 0) reading from `/sys/class/meizu/ps/ps_data` into the appropriately named `ps_calibration` file, in despair, and it magically worked... Release scheduled in ~3 days. And I'm closing this as "fixed", as no elegant solution is possible because the kernel side of this differs from the released Ubuntu Edition's kernel source.

**Closed as completed by xen0n** 2015-10-13 16:34 UTC
